### ISSUE TITLE
更新到2.1.4版本

### ISSUE THREAD

**Issue by noeXzTi** [laoyur/Undecimus-CN#1]
pwn20wnd已经把unc0ver更新到2.1.4了。

**Comment by laoyur** [comment]
已弃坑，因为unc0ver更新实在太快，还各种beta，懒得follow它了

还对此解决方案耿耿于怀的朋友，直接用deb吧：
https://github.com/laoyur/Undecimus-CN/raw/master/Undecimus/resources/com.laoyur.network-fixer.deb

新越狱后，一般都有openssh的，把deb scp到机器上，安装，运行一次即可：
```
scp com.laoyur.network-fixer.deb root@YOUR_IP:/tmp/
ssh root@YOUR_IP

# run on your device
dpkg -i /tmp/com.laoyur.network-fixer.deb
NetworkFixer com.saurik.Cydia
```

**Comment by laoyur** [comment]
假如有人运气好能看到的话：

⤵️更新了for iOS 11 + 12的版本
https://github.com/pwn20wndstuff/Undecimus/issues/136#issuecomment-470751673
